name: Debug DACFx Installation

on: [push, pull_request]
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  test-dacfx:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create temporary directory
        run: |
          mkdir D:\temp

      - name: Download DACFx Installer
        run: |
          $dacfxUrl = "https://aka.ms/dacfx-msi"
          $tempFile = "D:\temp\dacfx-installer.msi"
          Write-Host "Downloading DACFx from $dacfxUrl..."
          Invoke-WebRequest -Uri $dacfxUrl -OutFile $tempFile
          if (-Not (Test-Path $tempFile)) {
              throw "DACFx installer was not downloaded successfully."
          }
        shell: pwsh

      - name: Install DACFx
        run: |
          $tempFile = "D:\temp\dacfx-installer.msi"
          Write-Host "Installing DACFx from $tempFile..."
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i $tempFile /quiet /norestart /log D:\temp\dacfx-install.log" -NoNewWindow -Wait
          Write-Host "DACFx installation completed."
        shell: pwsh

      - name: Verify DACFx Installation Directory
        run: |
          $dacfxPath = "C:\Program Files\Microsoft SQL Server\160\DAC\bin\sqlpackage.exe"
          if (-Not (Test-Path $dacfxPath)) {
              throw "sqlpackage.exe not found in the expected installation directory: $dacfxPath"
          } else {
              Write-Host "sqlpackage.exe found in $dacfxPath"
          }
        shell: pwsh

      - name: Add DACFx to PATH
        run: |
          $dacfxPath = "C:\Program Files\Microsoft SQL Server\160\DAC\bin"
          [System.Environment]::SetEnvironmentVariable("PATH", $dacfxPath + ";" + $env:PATH, [System.EnvironmentVariableTarget]::Process)
          Write-Host "Added DACFx to PATH: $dacfxPath"
        shell: pwsh

      - name: Verify DACFx Command
        run: |
          if (-Not (Get-Command sqlpackage -ErrorAction SilentlyContinue)) {
              throw "DACFx installation failed. 'sqlpackage' command not found."
          } else {
              Write-Host "DACFx installed successfully."
          }
        shell: pwsh

      - name: Clean up temporary files
        run: |
          Remove-Item -Path D:\temp -Recurse -Force
        shell: pwsh
