name: Test ripgrep installation and size

on: [push, pull_request]

jobs:
  ubuntu-test:
    name: Install and test ripgrep on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install ripgrep via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Check ripgrep version
        run: rg --version

      - name: Check size of rg binary
        run: du -h $(which rg)

      - name: Test ripgrep
        run: |
          echo -e "hello\nthis is a test\nripgrep test line" > test.txt
          rg "test" test.txt

  windows-test:
    name: Install and test ripgrep on Windows
    runs-on: windows-latest
    steps:
      - name: Install ripgrep via Chocolatey
        run: choco install ripgrep -y

      - name: Check ripgrep version
        run: rg --version

      - name: Check size of rg.exe binary
        shell: pwsh
        run: |
          $size = (Get-Item "C:\ProgramData\chocolatey\bin\rg.exe").Length / 1MB
          Write-Output ("Size of rg.exe: {0:N2} MB" -f $size)

      - name: Test ripgrep
        run: |
          echo line with test content > test.txt
          rg test test.txt
