name: Ripgrep Runtime Install and Size Check

on: [push, pull_request]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install ripgrep
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep

      - name: Check ripgrep version
        run: rg --version

      - name: Check ripgrep binary size
        run: du -h $(which rg)

      - name: Test ripgrep functionality
        run: |
          echo -e "line1\ntest line\nanother" > sample.txt
          rg test sample.txt

  windows-test:
    runs-on: windows-latest
    steps:
      - name: Install ripgrep via Chocolatey
        run: choco install ripgrep -y

      - name: Check ripgrep version
        run: rg --version

      - name: Get actual ripgrep binary size
        shell: pwsh
        run: |
          $installPath = "C:\ProgramData\chocolatey\lib\ripgrep\tools"
          $totalSizeBytes = (Get-ChildItem -Recurse $installPath | Measure-Object -Property Length -Sum).Sum
          $totalSizeMB = "{0:N2} MB" -f ($totalSizeBytes / 1MB)
          Write-Output "Actual ripgrep install size: $totalSizeMB"

      - name: Test ripgrep functionality
        run: |
          echo line1 > test.txt
          echo test match >> test.txt
          rg test test.txt
